print(4+3)
print(4-3)
print(3*4)
print(4%3)
print(4/3)
print(4**3)
print(3//4)


print("Daren")
print("Filipov")
print("Bulgaria")
print("I am enjoying 30 days of python")

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type(['Asabeneh', 'Python', 'Finland']))
print(type("Daren"))
print(type("Filipov"))
print(type("Bulgaria"))
